#!/bin/bash

sleep 5m
amixer set Master 100%
sleep 1s
mplayer /home/blackout/.sounds/alarm.mp3
sleep 1s
amixer set Master 50%
echo " "
echo " Ramen is ready!"
echo " "
zenity --warning --text "Ramen is ready!"
exit 0
