#!/bin/bash

sleep 8h
mplayer /home/blackout/.sounds/alarm.mp3
sleep 1s
echo " "
echo " Wake up, Neo... The Matrix has you... Follow the white rabbit. Knock, knock, Neo."
echo " "
zenity --warning --text "Wake up!"
exit 0
