#!/bin/bash

sleep 40m
amixer set Master 100%
sleep 1s
mplayer /home/blackout/.sounds/alarm.mp3
sleep 1s
amixer set Master 50%
sleep 1s
echo " "
echo " Turn off the water pump!"
echo " "
zenity --warning --text "Turn off the water pump!"
exit 0
